/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package continuitytest;

/**
 *
 * @author Chaurasia
 */
public class Settings extends javax.swing.JInternalFrame {

    Main mRef;
    /**
     * Creates new form Settings
     */
    public Settings(Main m) {
        initComponents();
        mRef=m;
        textMaxCapacity.setText(String.valueOf(mRef.getMaxSize()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelHeaderText = new javax.swing.JLabel();
        labelMaxBlockCapacity = new javax.swing.JLabel();
        textMaxCapacity = new javax.swing.JTextField();
        btnUpdateMaxBlockSize = new javax.swing.JButton();

        setClosable(true);

        labelHeaderText.setText("Setting Panel");

        labelMaxBlockCapacity.setText("Set Max Capacity of Block ");

        btnUpdateMaxBlockSize.setText("Update");
        btnUpdateMaxBlockSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateMaxBlockSizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUpdateMaxBlockSize)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelHeaderText)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelMaxBlockCapacity)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textMaxCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelHeaderText)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMaxBlockCapacity)
                    .addComponent(textMaxCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdateMaxBlockSize)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateMaxBlockSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMaxBlockSizeActionPerformed

 
int newSize=Integer.valueOf(mRef.getMaxSize());
mRef.setMaxSize(newSize);
mRef.ConsoleMsg("Container Size Updated");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateMaxBlockSizeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdateMaxBlockSize;
    private javax.swing.JLabel labelHeaderText;
    private javax.swing.JLabel labelMaxBlockCapacity;
    private javax.swing.JTextField textMaxCapacity;
    // End of variables declaration//GEN-END:variables
}
